a = input()
b = input()
result = a + b
paint(a, "+", b, "=", result)
result = a - b
paint(a, "-", b, "=", result)
result = a * b
paint(a, "*", b, "=", result)
result = a / b
paint(a, "/", b, "=", result)
